from sqlalchemy import Column, String, Float, Integer
from backend.app.db.database import Base

class Telemetry(Base):
    __tablename__ = "telemetry"

    id = Column(Integer, primary_key=True, autoincrement=True)
    timestamp = Column(String, index=True)
    shift_id = Column(String, index=True)
    machine_id = Column(String, index=True)
    operator_id = Column(String, index=True)
    machine_type = Column(String)
    task_id = Column(String)
    engine_hours = Column(Float)
    engine_rpm = Column(Float)
    engine_load = Column(Float)
    fuel_level = Column(Float)
    fuel_consumption_rate = Column(Float)
    hydraulic_temperature = Column(Float)
    coolant_temperature = Column(Float)
    hydraulic_pressure = Column(Float)
    machine_speed = Column(Float)
    machine_direction = Column(String)
    machine_state = Column(String)
    idle_time_seconds = Column(Float)
    cycle_time_seconds = Column(Float)
    payload_tonnes = Column(Float)
    bucket_load_percent = Column(Float)
    number_of_cycles = Column(Integer)
    operating_mode = Column(String)
    latitude = Column(Float)
    longitude = Column(Float)
    site_zone = Column(String)
    terrain_slope_degrees = Column(Float)
    vibration = Column(Float)
    ambient_temperature = Column(Float)
    rainfall_mm = Column(Float)
    visibility_meters = Column(Float)
    wind_speed = Column(Float)
    seatbelt_status = Column(String)
    proximity_distance_meters = Column(Float)
    nearby_person_count = Column(Integer)
    nearby_vehicle_count = Column(Integer)
    fault_code = Column(String)
    machine_health_score = Column(Float)
    task_progress_percent = Column(Float)
    site_congestion = Column(Float, default=0.2)
