# Safety and System Constants

SEVERITY_CRITICAL = "CRITICAL"
SEVERITY_WARNING = "WARNING"
SEVERITY_INFO = "INFO"

MACHINE_STATE_OPERATING = "operating"
MACHINE_STATE_IDLE = "idle"
MACHINE_STATE_REVERSING = "reversing"
MACHINE_STATE_PARKED = "parked"

# Risk score thresholds
RISK_THRESHOLD_INFO_MAX = 29
RISK_THRESHOLD_WARNING_MAX = 59
RISK_THRESHOLD_CRITICAL_MIN = 60

# Reversing proximity hazard limits (meters)
CRITICAL_PROXIMITY_DISTANCE_DEFAULT = 5.0
CRITICAL_PROXIMITY_DISTANCE_RAIN = 7.5
DYNAMIC_SAFE_DISTANCE_FACTOR = 0.85
